#!/bin/sh
domain=peknight.com
while getopts :d: opt
do
    case "$opt" in
        d) domain=$OPTARG;;
        *) echo "Unknown option: $opt";;
    esac
done
target_dir=/root/software/acme.sh
if [ ! -d "$target_dir/out" ]; then
  mkdir -p $target_dir/out
fi
docker run --rm -it --name pek-acme-revoke -h pek-acme-revoke -v $target_dir/out:/acme.sh --net host neilpang/acme.sh --revoke -d ${domain} --ecc
