#!/bin/sh
target_dir=/root/software/acme.sh
if [ ! -d "$target_dir/out" ]; then
  mkdir -p $target_dir/out
fi
docker run -itd --name pek-acme-daemon -h pek-acme-daemon -v $target_dir/out:/acme.sh --net host neilpang/acme.sh daemon
