#!/bin/bash
docker exec pek-acme-daemon --install-cert -d peknight.com -d *.peknight.com -d *.server.peknight.com -d *.v6.server.peknight.com -d *.ctrl.peknight.com -d *.vpn.peknight.com -d *.v6.vpn.peknight.com -d pek.ink -d *.pek.ink -d pek.space -d *.pek.space --fullchainpath /install/nginx.crt --keypath /install/nginx.key --ecc
