#!/bin/bash
# Usage: chmodr -d 755 -f 644 .
while getopts :d:f: opt
do
    case "$opt" in
        d) dirmod=$OPTARG;;
        f) filemod=$OPTARG;;
        *) echo "Unknown option: $opt"
    esac
done
shift $[ $OPTIND - 1 ]

while [ -n "$1" ]
do
    if [ -d "$1" ]
    then
        if [ -n "$dirmod" ]
        then
            find $1 -type d -exec chmod $dirmod {} \;
            echo "change dir[$1]: dirmod $dirmod"
        fi
        if [ -n "$filemod" ]
        then
            find $1 -type f -exec chmod $filemod {} \;
            echo "change dir[$1]: filemod $filemod"
        fi
    else
        echo "Invalid dir: $1" >&2
    fi
    shift
done
