#!/bin/bash
target_dir=.
target_lang=java
thrift_version=latest
while getopts :d:l:v: opt
do
    case "$opt" in
        d) target_dir=$OPTARG;;
        l) target_lang=$OPTARG;;
        v) thrift_version=$OPTARG;;
        *) echo "Unknown option: $opt";;
    esac
done
shift $(($OPTIND-1))
target_idl=$1

if [ ! -f "${target_idl}" ]; then
    echo "${target_idl} does not exist"
    exit 1
fi

if [ ! -d "${target_dir}" ]; then
    mkdir -p ${target_dir}
    if [ $? -ne 0 ]; then
        echo "${target_dir} invalid path"
        exit 1
    fi
fi

idl_name=$(basename ${target_idl})
if [ ! -e "${target_dir}/${idl_name}" ]; then
    cp ${target_idl} ${target_dir}/
fi

real_dir=$(readlink -f ${target_dir})

echo "docker run --rm --name pek-thrift -h pek-thrift -u $(id -u):$(id -g) -v ${real_dir}:/data thrift:${thrift_version} thrift -o /data --gen ${target_lang} /data/${idl_name}"
docker run --rm --name pek-thrift -h pek-thrift -u $(id -u):$(id -g) -v ${real_dir}:/data thrift:${thrift_version} thrift -o /data --gen ${target_lang} /data/${idl_name}
